-- =============================================================================
-- LILAM_GRAFANA: Beispiel-Consumer, der LILAM-Alerts an Grafana weiterreicht
--
-- Aufruf (SQL*Plus / SQLcl), angemeldet am Schema von LILAM:
--   @<pfad>/consumer/lilam_grafana/install_lilam_grafana.sql
--
-- Voraussetzungen: LILAM installiert (Tabelle LILAM_ALERTS), EXECUTE auf DBMS_ALERT,
--                  fuer echten HTTP-Versand zusaetzlich EXECUTE auf UTL_HTTP und eine Netzwerk-ACL.
-- Legt an: Tabelle LILAM_GRAFANA_OUTBOX (falls nicht vorhanden), Package LILAM_GRAFANA.
-- =============================================================================
set serveroutput on

-- Ausgang: jede an Grafana gerichtete Annotation. Ohne URL ist diese Tabelle der "imaginaere Grafana-Dienst".
create table if not exists lilam_grafana_outbox (
    outbox_id     number generated by default as identity primary key,
    alert_id      number not null,
    target_url    varchar2(500),
    request_body  clob constraint lilam_grafana_outbox_json check (request_body is json),
    http_status   number,
    send_status   varchar2(20),          -- SIMULATED, SENT, FAILED
    error_message varchar2(2000),
    created_at    timestamp default systimestamp
);

create index if not exists lilam_grafana_outbox_alert on lilam_grafana_outbox (alert_id);

@@LILAM_GRAFANA.pks
@@LILAM_GRAFANA.pkb

show errors package lilam_grafana
show errors package body lilam_grafana
